export const ITEM_CATALOG = [
  // HAIR
  {
    id: 'hair_curly',
    name: 'Cozy Curls',
    category: 'hair',
    cost: 0,
    unlockedByDefault: true,
    description: 'Messy, charming warm brown curls.',
    icon: '🦱',
  },
  {
    id: 'hair_bob',
    name: 'Librarian Bob',
    category: 'hair',
    cost: 0,
    unlockedByDefault: true,
    description: 'Neat, academic bob cut with honey undertones.',
    icon: '💇',
  },
  {
    id: 'hair_ponytail',
    name: 'High Ponytail',
    category: 'hair',
    cost: 20,
    unlockedByDefault: false,
    description: 'Brisk, focused ponytail ready for serious study.',
    icon: '👱',
  },
  {
    id: 'hair_beanie',
    name: 'Winter Beanie',
    category: 'hair',
    cost: 35,
    unlockedByDefault: false,
    description: 'Warm knit mustard beanie keeping thoughts cozy.',
    icon: '🧶',
  },
  {
    id: 'hair_bee_antenna',
    name: 'Golden Bee Antennae',
    category: 'hair',
    cost: 50,
    unlockedByDefault: false,
    description: 'Cute, twitching golden bee antennae band.',
    icon: '🐝',
  },

  // OUTFITS
  {
    id: 'outfit_sweater',
    name: 'Honey Knit Sweater',
    category: 'outfit',
    cost: 0,
    unlockedByDefault: true,
    description: 'Chunky honey-gold cable-knit woolen sweater.',
    icon: '🧥',
  },
  {
    id: 'outfit_vest',
    name: 'Academic Cardigan',
    category: 'outfit',
    cost: 0,
    unlockedByDefault: true,
    description: 'Classic dark oak professor sweater vest.',
    icon: '👔',
  },
  {
    id: 'outfit_bee_hoodie',
    name: 'Striped Bee Hoodie',
    category: 'outfit',
    cost: 30,
    unlockedByDefault: false,
    description: 'Cozy oversized hoodie with bee stripes.',
    icon: '🐝',
  },
  {
    id: 'outfit_dungarees',
    name: 'Corduroy Overalls',
    category: 'outfit',
    cost: 40,
    unlockedByDefault: false,
    description: 'Vintage library overalls with notebook pockets.',
    icon: '👖',
  },
  {
    id: 'outfit_royal_bee',
    name: 'Queen Bee Robes',
    category: 'outfit',
    cost: 65,
    unlockedByDefault: false,
    description: 'Regal velvet royal robe trimmed in honeycomb lace.',
    icon: '👑',
  },

  // ACCESSORIES
  {
    id: 'acc_none',
    name: 'No Accessory',
    category: 'accessory',
    cost: 0,
    unlockedByDefault: true,
    description: 'Clean and unadorned.',
    icon: '✨',
  },
  {
    id: 'acc_glasses',
    name: 'Round Tortoise Glasses',
    category: 'accessory',
    cost: 0,
    unlockedByDefault: true,
    description: 'Scholarly round spectacles with golden frames.',
    icon: '👓',
  },
  {
    id: 'acc_flower',
    name: 'Amber Daisy Clip',
    category: 'accessory',
    cost: 15,
    unlockedByDefault: false,
    description: 'Fresh amber blossom pinned tucked behind the ear.',
    icon: '🌼',
  },
  {
    id: 'acc_scarf',
    name: 'Cozy Wool Scarf',
    category: 'accessory',
    cost: 25,
    unlockedByDefault: false,
    description: 'Thick tartan scarf for chilly library alcoves.',
    icon: '🧣',
  },
  {
    id: 'acc_crown',
    name: 'Honeycomb Crown',
    category: 'accessory',
    cost: 60,
    unlockedByDefault: false,
    description: 'A shimmering hexagon crown of crystallised honey.',
    icon: '👑',
  },

  // DESK DECORATIONS
  {
    id: 'decor_none',
    name: 'Empty Desk Surface',
    category: 'deskDecor',
    cost: 0,
    unlockedByDefault: true,
    description: 'Clean minimalist wood.',
    icon: '🪵',
  },
  {
    id: 'decor_mug',
    name: 'Steaming Honey Mug',
    category: 'deskDecor',
    cost: 0,
    unlockedByDefault: true,
    description: 'Warm porcelain mug of chamomile tea with raw honey.',
    icon: '☕',
  },
  {
    id: 'decor_succulent',
    name: 'Potted Succulent',
    category: 'deskDecor',
    cost: 15,
    unlockedByDefault: false,
    description: 'Cute miniature potted jade plant in terracotta.',
    icon: '🪴',
  },
  {
    id: 'decor_candle',
    name: 'Beeswax Candle',
    category: 'deskDecor',
    cost: 25,
    unlockedByDefault: false,
    description: 'Aromatic flickering candle that smells like clover honey.',
    icon: '🕯️',
  },
  {
    id: 'decor_trophy',
    name: 'Golden Scholar Bee',
    category: 'deskDecor',
    cost: 50,
    unlockedByDefault: false,
    description: 'A glittering golden bee trophy commemorating study streaks.',
    icon: '🏆',
  },
];

export const DEFAULT_OWNED_ITEMS = ITEM_CATALOG
  .filter((i) => i.unlockedByDefault)
  .map((i) => i.id);

export const DEFAULT_EQUIPPED_ITEMS = {
  hair: 'hair_curly',
  outfit: 'outfit_sweater',
  accessory: 'acc_glasses',
  deskDecor: 'decor_mug',
};
